name: Generate Demos

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: main

    - uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build .

    - name: Install VHS
      run: go install github.com/charmbracelet/vhs@latest
  
  Record receiver:
    runs-on: ubuntu-latest
    needs: [Setup]
    steps:
    - name: Record receiver
      run: vhs receiver_demo.tape

  Record sender:
    runs-on: ubuntu-latest
    needs: [Setup]
    steps:
    - name: Download a 200MB test file
      run: curl -LJO http://ipv4.download.thinkbroadband.com/200MB.zip

    - name: Record sender
      run: vhs sender_demo.tape

  - name: Commit and push
      run: |-
        cd main
        git config --global user.email "actions@users.noreply.github.com"
        git config --global user.name "DEMO-bot"
        git add sender_demo.gif receiver_demo.gif && git commit -m "Updated Demo"
        git push