name: Generate Demos

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Build
      run: go build .

    - name: Install VHS
      run: go install github.com/charmbracelet/vhs@latest
  
  record-receiver:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
    - name: Record receiver
      run: vhs receiver_demo.tape

  record-sender:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
    - name: Download a 200MB test file
      run: curl -LJO http://ipv4.download.thinkbroadband.com/200MB.zip

    - name: Record sender
      run: vhs sender_demo.tape

  Commit:
    runs-on: ubuntu-latest
    needs: [record-receiver, record-sender]
    steps:
    - run: |-
        cd main
        git config --global user.email "actions@users.noreply.github.com"
        git config --global user.name "DEMO-bot"
        git add sender_demo.gif receiver_demo.gif && git commit -m "Updated Demo"
        git push